export const FST_FETCH_PROFILE = 'FST_FETCH_PROFILE';
export const FST_SET_ERROR = 'FST_SET_ERROR';
export const FST_SET_PROFILE = 'FST_SET_PROFILE';
export const FST_SET_SEARCH_VALUE = 'FST_SET_SEARCH_VALUE';
export const FST_TOGGLE_TO_COMPARE = 'FST_TOGGLE_TO_COMPARE';